### ISSUE TITLE
Processing 'xx' failed.

### ISSUE THREAD

**Issue by provegard** [ermshiperete/BuildTasks.TextTemplating#1]
When there is an error in a tt file, the error message in the title is all I get. It would be nice to have the full error message, if possible.

Currently you have to right-click on the offending file and invoke the custom build tool manually.

**Comment by provegard** [comment]
It also appears as if the transformations happens before the DLL or its dependencies are built, which means that a template cannot depend on classes in the current or another assembly. Is that correct?

**Comment by ermshiperete** [comment]
> It also appears as if the transformations happens before the DLL or its dependencies are built, which means that a template cannot depend on classes in the current or another assembly. Is that correct?

Yes, that is correct. You can't depend on classes in the current assembly. Maybe you could depend on classes in another assembly of the same solution if you fiddle around with the target dependencies in the .csproj files (see BuildTasks.TextTemplating.targets), but I haven’t' tried that.

You CAN definitely depend on  assemblies built outside of the current solution.

**Comment by ermshiperete** [comment]
Fixed in NuGet package version 1.1.0
